### ISSUE TITLE
Evaluator does not recognize autoloads

### ISSUE THREAD

**Issue by rxlecky** [rxlecky/godot#1]

**Comment by rxlecky** [comment]
@jahd2602 the autoloads now work with evaluator.  They, however, can only be evaluated when the game is running - even if the autoload is `tool` script. Is this something you'd find use for? Or is it a low priority?

Besides that, evaluating autoloads in watches causes crash or wil. I will be working on fixing this asap.

**Comment by jahd2602** [comment]
@rxlecky those are great news! the `tool` script use case is very low priority.

I can't wait to see the autoloads working in the watches. Great work!
